// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/repository/reports.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	entity "finance-tg-bot/internal/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// GetStatementCatTotals mocks base method.
func (m *MockReporter) GetStatementCatTotals(ctx context.Context, p map[string]string) ([]entity.ReportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatementCatTotals", ctx, p)
	ret0, _ := ret[0].([]entity.ReportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatementCatTotals indicates an expected call of GetStatementCatTotals.
func (mr *MockReporterMockRecorder) GetStatementCatTotals(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatementCatTotals", reflect.TypeOf((*MockReporter)(nil).GetStatementCatTotals), ctx, p)
}

// GetUserStats mocks base method.
func (m *MockReporter) GetUserStats(ctx context.Context, user_id int) (entity.UserStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStats", ctx, user_id)
	ret0, _ := ret[0].(entity.UserStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStats indicates an expected call of GetUserStats.
func (mr *MockReporterMockRecorder) GetUserStats(ctx, user_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStats", reflect.TypeOf((*MockReporter)(nil).GetUserStats), ctx, user_id)
}
